# Generated by Django 2.0 on 2020-05-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('soft_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
